# Generated by Django 4.0.5 on 2022-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.DateField()),
                ('expense', models.IntegerField()),
                ('cleaningStaff_per_day', models.IntegerField()),
                ('cookingStaff_per_day', models.IntegerField()),
            ],
        ),
    ]
